### ISSUE TITLE
Cannot instantiate classes within spore body

### ISSUE THREAD

**Issue by phaller** [jvican/spores-spark#22]
It seems that right now it's not possible to instantiate classes within spores, which is a severe restriction. This must be an oversight since I doubt spores would be very useful without being able to create instances within their bodies. (Btw, this is a regression compared to early versions of spores.)

Currently, the following test is rejected:
```scala
class Box {
  def open(fun: Spore[Int, Unit]): Unit = {
    fun(5)
  }
}
class NonSneaky {
  def process(a: Array[Int]): Unit = {
    for (i <- 0 until a.length)
      a(i) = a(i) + 1
  }
}
@RunWith(classOf[JUnit4])
class NewTestsSpec {
  @Test def createHarmlessInstance(): Unit = {
    val b = new Box
    b.open(spore { (x: Int) =>
      // OK: create instance of harmless class
      val ns = new NonSneaky
    })
  }
}
```

The reported error is:
```
[error] ...: Spore contains references to an invalid symbol: class NonSneaky.
[error]       val ns = new NonSneaky
[error]
```

I pushed the complete, executable test case to [a branch on my fork](https://github.com/phaller/spores/tree/create-harmless-instance).

**Comment by phaller** [comment]
ping @jvican

**Comment by jvican** [comment]
Indeed, this is an oversight. Will fix soon.

**Comment by phaller** [comment]
OK, great. Thanks, @jvican!
